### ISSUE TITLE
[Epic] Make Lightning App fully Serverless

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/lightning#13672]
## 🚀 Feature

In order to optimize cost at scale, it is important Lightning App becomes fully serverless.

Terminology: ``Serverless`` means there is a cost occurring when nothing is happing. This movement democratized by the cloud is known as ``Pay as you Go`` Services.

Making Apps Serverless is challenging but would enable more complex systems to be built at the fraction of the cost.

 ## Actions Items:
 
 ### Trainer, LightningModule
 - [] Implement Last Minute PL Fault Tolerance: This feature enables Fault Tolerance to be enabled last minute once receiving a SIGTERM signal, collecting all metadata, applying 1 extra baches and stop after generating an auto_restart checkpoints    

 
 ### Flow, Work
- [] Auto Restart: Works should be restartable. Introduce the self.restarting and checkpointing logic
- [] Add support for a PyTorchLightningPythonScript Component.
- [] Enable Flow portability. The flow should be restartable from one process to another, one machine to another
- [] Frontends Load Balancing: Frontend should be turned down when there aren't any incoming requests and restarted otherwise.
- [] State Arching: The state can grow quickly as an app is running and dynamically creating resources. The partial part of the state could be archived when not accessed for some time.
- [] Introduce Work Deletion: When work is deleted, resources should be stopped and the state removed from the App.  

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.
