### ISSUE TITLE
🚀 Remove deprecated APIs for 1.8 release 

### ISSUE THREAD

**Issue by krishnakalyan3** [Lightning-AI/lightning#14841]
Let's remove the deprecated [1.8 APIs](https://github.com/Lightning-AI/lightning/blob/master/tests/tests_pytorch/deprecated_api/test_remove_1-8.py) together. This is a single place where we can easily track the status of the API.

Please, comment on this issue in order to reserve a particular file to work on. Once you do so, I will edit this top comment to avoid collisions. Once you think your work is finished, please open a PR referencing this issue.

Please note, that it can happen that you may need to edit more than just one file. This is fine, but please keep in mind, that the goal of your PR will be to make the check pass for the chosen file. 

The steps to remove deprecated APIs below
- Decide on the [test](https://github.com/Lightning-AI/lightning/blob/master/tests/tests_pytorch/deprecated_api/test_remove_1-8.py) you want to remove
- grep for all the occurrences of deprecation in the source code and remove
- update [changelog](https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/CHANGELOG.md)
- make sure that unit tests pass

Example - #14833

For those of you who are not familiar with the process of contributing a PR, we have prepared a [simple guide](https://devblog.pytorchlightning.ai/quick-contribution-guide-86d977171b3a) that will walk you through the necessary steps. You can do it! 🚀 💪

- [x] test_v1_8_0_on_init_start_end #14867
- [x] test_v1_8_0_deprecated_call_hook #14869
- [x] test_v1_8_0_deprecated_run_stage #14870
- [x] test_v1_8_0_trainer_verbose_evaluate #14884
- [x] test_v1_8_0_trainer_ckpt_path_attributes #14897
- [x] test_v1_8_0_deprecated_trainer_should_rank_save_checkpoint #14885
- [x] test_v1_8_0_trainer_optimizers_mixin #14887
- [x] test_v1_8_0_deprecate_trainer_data_loading_mixin #14888
- [x] test_v_1_8_0_deprecated_device_stats_monitor_prefix_metric_keys #14890
- [x] test_v1_8_0_deprecated_lightning_optimizers #14889
- [x] test_v1_8_0_remove_on_batch_start_end #14834
- [x] test_v1_8_0_on_configure_sharded_model #14834
- [x] test_v1_8_0_remove_on_epoch_start_end_lightning_module #14834
- [x] test_v1_8_0_remove_on_pretrain_routine_start_end_lightning_module #14834
- [x] test_v1_8_0_on_before_accelerator_backend_setup #14834
- [x] test_v1_8_0_logger_agg_parameters #14840
- [x] test_v1_8_0_deprecated_agg_and_log_metrics_override #14840
- [x] test_v1_8_0_callback_on_pretrain_routine_start_end #14834
- [x] test_simple_profiler_iterable_durations #14864
- [x] test_v1_8_0_datamodule_checkpointhooks #14909
- [x] test_v1_8_0_deprecated_lightning_ipu_module #14830
- [ ] test_v1_8_0_callback_on_load_checkpoint_hook  #14835
- [ ] test_v1_8_0_callback_on_save_checkpoint_hook #14835

This issue is inspired by the community effort in #13445

**Comment by awaelchli** [comment]
Hey @krishnakalyan3 thanks for opening the PR. But let's be clear, this is not about deprecating APIs for 1.8. Here we are talking about _removals_ of APIs that were already deprecated in past releases.

**Comment by krishnakalyan3** [comment]
Yes. thanks for clarifying the description.
